### ISSUE TITLE
Tags are not always built

### ISSUE THREAD

**Issue by tamouse** [rmcfadzean/gatsby-pantry#1]
I'm seeing an inconsistency in how tag pages are created, and I really don't understand what is going on. In most cases, after doing a `yarn build`, the only tags in the `public/tags/` directory are from one page in `src/pages/`, although a few of them have tags. The resulting tags are also inconsistent, as if only one of the pages' tags is being used.

The following repo exhibits the problem: <https://github.com/tamouse/gatsby-tamouse-blog/tree/components> in the `components` branch.

I've forced in the `public/` directory into the repo, so the limited number of tag pages can be shown.

**Comment by rmcfadzean** [comment]
Hey @tamouse! Sorry about the delay and thank you for the report! I just pushed a new version (1.1.2) which I believe fixes the issues you were having. Feel free to re-open this issue if it doesn't.
