### ISSUE TITLE
Categories not working, tags does.

### ISSUE THREAD

**Issue by exocode** [rmcfadzean/gatsby-pantry#223]
I copy pasted everything from the example-blog to my page, `tags` and `slug` are showing up in `fields` but `categories `not

```
There was an error in your GraphQL query:

Field "category" is not defined by type MarkdownRemarkFieldsFilterInput.

File: /Users/jan/Coding/React/page.com/src/templates/blog-category.js

There was an error in your GraphQL query:

Field "slug" is not defined by type MarkdownRemarkFieldsFilterInput.

File: /Users/jan/Coding/React/page.com/src/templates/blog-post.jsx

There was an error in your GraphQL query:

Cannot query field "slug" on type "MarkdownRemarkFields".

If you don't expect "slug" to exist on the type "MarkdownRemarkFields" it is most likely a typo.
However, if you expect "slug" to exist there are a couple of solutions to common problems:
´´´

Why does it not render?

`category: "Some Category"` are in each of my ".md" files

```
    "gatsby": "^2.22.15",
    "gatsby-plugin-categories": "^2.3.7",
    "gatsby-plugin-tags": "^2.3.7",
```

**Comment by exocode** [comment]
I took 7 hours to find out, that your demo is running on 2.3.5 and 2.3.7 is latest. PLEASE update your demo starter blog to your recent version. It seems to make problems while tags are created....

**Comment by rmcfadzean** [comment]
Hi @exocode thanks for opening the issue. I'll happily accept PRs for this but unfortunately I don't use (or really recommend) these plugins anymore. They've very limited in their use and I find myself always tweaking them for clients anyway.
