### ISSUE TITLE
Can't see example gatsby-plugin-categories on document

### ISSUE THREAD

**Issue by NantipatSoftEn** [rmcfadzean/gatsby-pantry#58]
Pls read this issues.
**https://github.com/gatsbyjs/gatsby/issues/16058**
some one can change URL example for correctly  ?

**Comment by rmcfadzean** [comment]
Hi @NantipatSoftEn 

Thanks for the report. Good catch! I have fixed the change on the README and it should propagate to gatsby's docs soon.

In the mean time, you can view the link here https://github.com/rmcfadzean/gatsby-pantry/tree/master/examples/starter-blog#readme

**Comment by NantipatSoftEn** [comment]
Thanks
