### ISSUE TITLE
How to reconcile gatsby-starter-blog and plugins for tags, categories?

### ISSUE THREAD

**Issue by BrunoVernay** [rmcfadzean/gatsby-pantry#6]
Hi,
I used the popular  gatsby-starter-blog  and then trying to use your plugin.
I have multiple errors: There is not `Posts`, no `../layout`, no `../components/PostListing` 

At first I also have an error with the `path.` that does not exist, but I could replace it with 
```
        name: "posts",
        path:  `${__dirname}/content/blog`,
```

Maybe the issue is with the [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog) (1097 stars) ? Since you plugins (tags & categories) seems to be well aligned with the documentation https://www.gatsbyjs.org/docs/adding-tags-and-categories-to-blog-posts/ ?

`PostListing` is missing too. I only found it in https://github.com/Vagr9K/gatsby-advanced-starter/blob/master/src/components/PostListing/PostListing.jsx  for example. But not even sure if it is the right one ...

**Comment by rmcfadzean** [comment]
Hi, Please see the new example I have added. If you're still having issues, feel free to reopen.

https://github.com/rmcfadzean/gatsby-pantry/blob/master/examples/starter-blog
